datitle: "My Portfolio"
description: "Welcome to my personal portfolio site!"
url: "https://your-username.github.io"
theme: jekyll-theme-minimal
author: "Brendan Coppinger"
email: "brendancopps@gmail.com"
logo: /assets/img/logo.png

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclusions
exclude:
  - README.md

# Custom Variables
social_links:
  github: "https://github.com/brendancopps7"
  linkedin: "https://www.linkedin.com/in/brendan-coppinger"
